### ISSUE TITLE
crosscluster/logical: some tests hang when run in a secondary tenant.

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#127241]
**Describe the problem**

Some tests seem to hang when we run against a secondary tenant, even after fixing all of the issues with SystemLevel cluster settings. The problem appears to be something related to descriptor leasing.

Jira issue: CRDB-40336

**Comment by stevendanna** [comment]
I think I mis-diagnosed this. It isn't tenant related. Still investigating.

**Comment by stevendanna** [comment]
The root cause was related to leases and was fixed in https://github.com/cockroachdb/cockroach/pull/127242/commits/5d786d47f1b936a556ebfc3aaec806f2318f8c20

**Comment by yuzefovich** [comment]
I still see the tests marked with issue fail with external-process mode.
