### ISSUE TITLE
sql: support error handling during result aggregations

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13640]
Currently the mechanism that accumulates results in the "aggregate function holders" does not support handling errors. So errors that happen during the aggregation operation have nowhere to go.

This is a problem, as found in #9709 and https://github.com/cockroachdb/cockroach/pull/13551#issuecomment-280570633.

**Comment by dianasaur323** [comment]
@knz moving into 1.0, but feel free to move out if you'd like

**Comment by justinj** [comment]
Addressed by #14904.

**Comment by mjibson** [comment]
This issue remains for the `Result` call. Would be nice to get this done by 1.0. See: https://github.com/cockroachdb/cockroach/blob/e8c5429a6727d603d074bbb3a72b91b8acd1afdb/pkg/sql/parser/aggregate_builtins.go#L348 (and others similar).
