### ISSUE TITLE
server: grant coordinators call GetMetrics on closed Pebble instances

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#140454]
I attempted to make a change in Pebble which cleared out the `fileCacheHandle` on `Close`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1156aba]

goroutine 61812 [running]:
github.com/cockroachdb/pebble.(*fileCacheHandle).metrics(0xc00301eb40)
	external/com_github_cockroachdb_pebble/file_cache.go:192 +0x1a
github.com/cockroachdb/pebble.(*DB).Metrics(0xc00baedb08)
	external/com_github_cockroachdb_pebble/db.go:2051 +0xe2a
github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).GetMetrics(_)
	pkg/storage/pebble.go:1842 +0x65
github.com/cockroachdb/cockroach/pkg/server.(*nodePebbleMetricsProvider).GetPebbleMetrics.func1(0xc004b21808)
	pkg/server/node.go:1391 +0x74
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores.func1(0x8f6d150?, 0xc0061e6150?)
	pkg/kv/kvserver/stores.go:146 +0x26
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*Map[...]).Range(0x8bd1ce0?, 0xc00b223d38)
	pkg/util/syncutil/map.go:391 +0x10d
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores(0x49f46e?, 0x1b3e47d?)
	pkg/kv/kvserver/stores.go:145 +0x55
github.com/cockroachdb/cockroach/pkg/server.(*nodePebbleMetricsProvider).GetPebbleMetrics(0xc00a41cf48)
	pkg/server/node.go:1389 +0x1a8
github.com/cockroachdb/cockroach/pkg/util/admission.(*StoreGrantCoordinators).SetPebbleMetricsProvider.func1()
	pkg/util/admission/grant_coordinator.go:120 +0x1bb
created by github.com/cockroachdb/cockroach/pkg/util/admission.(*StoreGrantCoordinators).SetPebbleMetricsProvider in goroutine 59280
	pkg/util/admission/grant_coordinator.go:96 +0x389
```

The engine closer is registered here:
https://github.com/cockroachdb/cockroach/blob/cada6b4976accfefa486b9e81804b2193f320fe8/pkg/server/server.go#L298

The grant coordinator closer is here:
https://github.com/cockroachdb/cockroach/blob/cada6b4976accfefa486b9e81804b2193f320fe8/pkg/server/server.go#L599

There are two problems:
 - closers don't run in reverse order (which seems wrong in general)
 - the grant coordinator closer doesn't actually wait for the background loop to exit (https://github.com/cockroachdb/cockroach/blob/cc8f6678e08b217c5926b6e8e82da774168c1739/pkg/util/admission/grant_coordinator.go#L278)

Jira issue: CRDB-47168

**Comment by RaduBerinde** [comment]
I reverted the change in Pebble which surfaced this in https://github.com/cockroachdb/pebble/commit/35df1961

**Comment by aadityasondhi** [comment]
@RaduBerinde do you think the PR we merged is enough to close this out https://github.com/cockroachdb/cockroach/pull/140479?

It fixes the `the grant coordinator closer doesn't actually wait for the background loop to exit`, but should we also fix the ordering in closers?

**Comment by RaduBerinde** [comment]
> It fixes the the grant coordinator closer doesn't actually wait for the background loop to exit

Does it though? It fixes the (more egregious) issue of having to wait a tick until we close.. but the Close path still doesn't explictly wait for the background goroutine to be done, no? (so this race is still a possibility)

Closers ordering is separate, I filed https://github.com/cockroachdb/cockroach/issues/142347 for that.

**Comment by iskettaneh** [comment]
I am not 100% sure if this is related, but I got this error when testing a change (Still in progress change):

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/19183735?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true

```
WARNING: DATA RACE
Read at 0x00c008f010f8 by goroutine 48323:
  github.com/cockroachdb/pebble/internal/genericcache.(*Cache[go.shape.struct { github.com/cockroachdb/pebble.handle *github.com/cockroachdb/pebble.fileCacheHandle; github.com/cockroachdb/pebble.fileNum github.com/cockroachdb/pebble/internal/base.DiskFileNum; github.com/cockroachdb/pebble.fileType github.com/cockroachdb/pebble/internal/base.FileType },go.shape.struct { github.com/cockroachdb/pebble.closeHook func(); github.com/cockroachdb/pebble.reader io.Closer; github.com/cockroachdb/pebble.isShared bool; github.com/cockroachdb/pebble.readerProvider github.com/cockroachdb/pebble.tableCacheShardReaderProvider }]).Metrics()
      external/com_github_cockroachdb_pebble/internal/genericcache/cache.go:162 +0x33
  github.com/cockroachdb/pebble.(*fileCacheHandle).Metrics()
      external/com_github_cockroachdb_pebble/file_cache.go:282 +0x4a
  github.com/cockroachdb/pebble.(*DB).Metrics()
      external/com_github_cockroachdb_pebble/db.go:2112 +0x2698
  github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).GetMetrics()
      pkg/storage/pebble.go:1818 +0x84
  github.com/cockroachdb/cockroach/pkg/server.(*nodePebbleMetricsProvider).GetPebbleMetrics.func1()
      pkg/server/node.go:1361 +0x9e
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores.func1()
      pkg/kv/kvserver/stores.go:146 +0x41
  github.com/cockroachdb/cockroach/pkg/util/syncutil.(*Map[go.shape.int32,go.shape.6307790ce6061e6718a397ca94049777a04171e8e185d2610287a4e1de09d632]).Range()
      pkg/util/syncutil/map.go:391 +0x210
  github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores()
      pkg/kv/kvserver/stores.go:145 +0x94
  github.com/cockroachdb/cockroach/pkg/server.(*nodePebbleMetricsProvider).GetPebbleMetrics()
      pkg/server/node.go:1359 +0x2b5
  github.com/cockroachdb/cockroach/pkg/util/admission.(*StoreGrantCoordinators).SetPebbleMetricsProvider.func1()
      pkg/util/admission/grant_coordinator.go:121 +0x317

Previous write at 0x00c008f010f8 by goroutine 43933:
  github.com/cockroachdb/pebble/internal/genericcache.(*Cache[go.shape.struct { github.com/cockroachdb/pebble.handle *github.com/cockroachdb/pebble.fileCacheHandle; github.com/cockroachdb/pebble.fileNum github.com/cockroachdb/pebble/internal/base.DiskFileNum; github.com/cockroachdb/pebble.fileType github.com/cockroachdb/pebble/internal/base.FileType },go.shape.struct { github.com/cockroachdb/pebble.closeHook func(); github.com/cockroachdb/pebble.reader io.Closer; github.com/cockroachdb/pebble.isShared bool; github.com/cockroachdb/pebble.readerProvider github.com/cockroachdb/pebble.tableCacheShardReaderProvider }]).Close()
      external/com_github_cockroachdb_pebble/internal/genericcache/cache.go:76 +0xfa
  github.com/cockroachdb/pebble.(*FileCache).Unref()
      external/com_github_cockroachdb_pebble/file_cache.go:429 +0x59
  github.com/cockroachdb/pebble.(*fileCacheHandle).Close()
      external/com_github_cockroachdb_pebble/file_cache.go:184 +0x44c
  github.com/cockroachdb/pebble.(*DB).Close()
      external/com_github_cockroachdb_pebble/db.go:1818 +0x13b9
  github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).Close()
      pkg/storage/pebble.go:1314 +0x1b8
  github.com/cockroachdb/cockroach/pkg/server.(*Engines).Close()
      pkg/server/config.go:694 +0x7b
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop()
      pkg/util/stop/stopper.go:565 +0x259
```

**Comment by RaduBerinde** [comment]
It does look related, crdb gets metrics while and after closing which is annoying. I'll take a look.
