### ISSUE TITLE
raft: `panic: applied(25) is out of range [prevApplied(10), committed(10)]`

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#1878]
Happened on my multicpu branch.

https://circleci.com/gh/cockroachdb/cockroach/5249

https://circle-artifacts.com/gh/cockroachdb/cockroach/5249/artifacts/0/tmp/circle-artifacts.6Xbc003/test.log

`TestRaftRemoveRace` specifically triggers this.

**Comment by bdarnell** [comment]
Looks like a race between GC and other raft operations, as discussed in #768 and #1865.

**Comment by tschottdorf** [comment]
one more for the inclined: https://circleci.com/gh/tschottdorf/cockroach/1347

**Comment by bdarnell** [comment]
I've reviewed all the linked logs and they all appear to be the same root cause, #768, which has been fixed by the combination of #2798 and #2823. Please open new issues if anything like this turns up again.

**Comment by tamird** [comment]
After rebasing #1839, I still see a failure in `TestRaftRemoveRace`:

> panic: [group 1] applied(54) is out of range [prevApplied(0), committed(0)]

https://circleci.com/gh/cockroachdb/cockroach/8440
https://circle-artifacts.com/gh/cockroachdb/cockroach/8440/artifacts/0/tmp/circle-artifacts.HHAR97f/test.log

**Comment by bdarnell** [comment]
Let's make that a new issue then - even though the message is similar, the underlying cause looks different and it's not helpful to continue in this thread. Also, all the others in this thread had non-zero values for `prevApplied` and `committed`
