### ISSUE TITLE
ui: display queries hitting each node

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#20571]
We recently had a user asking why a node was serving more queries than others, and it's a bit difficult to figure out without diving into debug pages why that is. We should surface this metric for debugging purposes. Probably something to explore later on. Marking as 1.3 for now.

**Comment by knz** [comment]
@couchand @vilterp I think the primary concern (why a node is serving more queries than others) is somewhat addressed now?

**Comment by couchand** [comment]
cc @piyush-singh

**Comment by vilterp** [comment]
Not quite solved until we have a graph of QPS and SQL connections broken down by node. Part of the per-node / aggregated toggle work (#27856)
