### ISSUE TITLE
cli/sql: string array does not handle unicode string well

### ISSUE THREAD

**Issue by kybin** [cockroachdb/cockroach#30911]
some korean characters (maybe also other unicode characters) are not saved/represented well if it's inside of a string array.

I did following from sql.

```
CREATE DATABASE temp;
set database = temp;
CREATE TABLE test (str STRING, strarray STRING[]);
INSERT INTO test (str, strarray) VALUES ('로이', ARRAY['로이']);
select * from test;
```

Then I saw this.
```
+------+------------------+
| str  |     strarray     |
+------+------------------+
| 로이 | {"\U0000B85C이"} |
+------+------------------+
```

The str column saves '로이' correctly, but strarray does not. It breaks '로' character.
There are many other korean characters that cockroach db does not handle well.

**Comment by jordanlewis** [comment]
Hi @kybin,

What version of Cockroach are you on? I can't reproduce this:

```
root@:26257/defaultdb> CREATE DATABASE temp;
CREATE DATABASE

Time: 6.484ms

root@:26257/defaultdb> set database = temp;
SET

Time: 909µs

root@:26257/temp> CREATE TABLE test (str STRING, strarray STRING[]);
CREATE TABLE

Time: 8.726ms

root@:26257/temp> INSERT INTO test (str, strarray) VALUES ('로이', ARRAY['로이']);
INSERT 1

Time: 7.242ms

root@:26257/temp> select * from test;;
+------+----------+
| str  | strarray |
+------+----------+
| 로이 | {"로이"} |
+------+----------+
(1 row)

Time: 8.207ms

root@:26257/temp>
```

**Comment by knz** [comment]
@kybin the issue you observe is that the special characters *are stored properly* in CockroachDb however the `cockroach sql` command is not able to display them properly inside an array.

For example, let me connect to a CockroachDB server using the `psql` command from PostgreSQL (CockroachDB server, pg client):

```
kena@kenax ~/cockroach % psql -U root -h localhost -p 26257
psql (10.5, server 9.5.0)
Type "help" for help.

root=>  CREATE TABLE test (str text, strarray text[]);
CREATE TABLE
root=> INSERT INTO test (str, strarray) VALUES ('로이', ARRAY['로이']);
INSERT 0 1
root=> select * from test;;
 str  | strarray
------+----------
 로이 | {"로이"}
(1 row)
```

As you can see the data is preserved.

@jordanlewis the problem exists in the latest 2.1 CLI client (even worse than reported):

```
root@127.0.0.1:49189/defaultdb> select * from test;;
  str  |           strarray
+------+------------------------------+
  로이 | {"\353\241\234\354\235\264"}
(1 row)
```

The problem (I think) is that the client should decode the values from the server into SQL values and then only print them.

**Comment by knz** [comment]
I also think this would not be as much an issue if the SQL driver we use had native support for arrays. Then the driver would decode the values properly and the CockroachDB shell would not have to do anything else. This is perhaps another argument in favor of migrating to pgx.

**Comment by kybin** [comment]
@jordanlewis It's v2.0.5

@knz Thank you for the detailed explanation!

**Comment by kybin** [comment]
Seems like this fixed in recent release, could you confirm it?

**Comment by knz** [comment]
In 2.1 the behavior is improved but not entirely fixed. However we did complete the fix, which will be available in 2.2

So you are right that the work is done. I will close this issue as a result.

Let us know if you notice anything that requires more work. Thank you!
