### ISSUE TITLE
roachtest: roachprod kill doesn't wait until process is actually dead

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31586]
**Describe the problem**

I ran tpccbench for tpcc 10k on a 9 node 64 cpu cluster on the 10/08 beta  and the 10/15 beta. I couldnt record any values for tpcc as I ran into workload problems. 

**To Reproduce**
```diff
index 071ef8a3fe..cd9858eeff 100644
--- a/pkg/cmd/roachtest/tpcc.go
+++ b/pkg/cmd/roachtest/tpcc.go
@@ -677,11 +677,11 @@ func registerTPCCBench(r *registry) {
                        // StoreDirVersion: "2.0-5",
                },
                {
-                       Nodes: 3,
-                       CPUs:  16,
+                       Nodes: 9,
+                       CPUs:  64,
 
-                       LoadWarehouses: 2000,
-                       EstimatedMax:   1300,
+                       LoadWarehouses: 10000,
+                       EstimatedMax:   8000,
                },
```
Then `make bin/roachtest` and finally `bin/roachtest bench '^tpccbench/nodes=9/cpu=64$$' --wipe=false --user=andy`

**Expected behavior**
Expected to ~ pass TPC-C 10K. 

**Additional data / screenshots**

**Environment:**
 - CockroachDB version 2.1 Beta 10/15

**Additional context**
Command line gist:
https://gist.github.com/awoods187/c1e5cfaac8088fa99b7e57b258916fd6

Logs
[Logs.zip](https://github.com/cockroachdb/cockroach/files/2492094/Logs.zip)

**Comment by awoods187** [comment]
10/15 Cluster: andy-1539833762-tpccbench-nodes-9-cpu-64

**Comment by awoods187** [comment]
10/08 Cluster: andy-1539820222-tpccbench-nodes-9-cpu-64
10/15 Cluster: andy-1539833762-tpccbench-nodes-9-cpu-64

**Comment by tschottdorf** [comment]
These are weird. The error is basically in both cases that the cockroach process fails because it can't get a lock on a temp dir:

> * ERROR: could not cleanup temporary directories from record file: could not lock temporary directory /mnt/data1/cockroach/cockroach-temp769974996, may still be in use: IO error: While lock file: /mnt/data1/cockroach/cockroach-temp769974996/TEMP_DIR.LOCK: Resource temporarily unavailable

From the logs I can see that the temp dir was the one used by the previous incarnation of the process, which was `kill -9`ed ~3s before. Or that's at least what it looked like -- the error is exactly the error you get if there *is* still a running CRDB instance for that directory.

The locks used are via rocksDB's env file log. I ssh'ed into one node and started the CRDB process, and it worked.

Ideally when this error occurs, we'd do some sleuthing to figure out if there is a process running. This would be possible since we store the `cockroach.{http,listen}-addr` file in the data directory and could probe the port.

**Comment by tschottdorf** [comment]
@mberhault is my understanding correct that once `kill -9` returns, the lock is immediately available?

**Comment by petermattis** [comment]
Unless the process didn’t actually die because it was stuck in a zombie
state. Historically I’ve seen that happen with network file systems. I
think killall has a “wait” flag. Perhaps we need something like that.

**Comment by mberhault** [comment]
`TEMP_DIR.LOCK` is controlled on the Go side and is unlocked in a stop closer (see https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/engine/temp_dir.go#L54).
This definitely won't get cleaned up on a `SIGKILL`

**Comment by petermattis** [comment]
I’m pretty sure there is an OS level file lock used there which will be
released when the process dies.

**Comment by benesch** [comment]
> I’m pretty sure there is an OS level file lock used there which will be released when the process dies.

Yes, that's right. Historically when we've had problems here it's been because we've deadlocked on ourselves.

**Comment by benesch** [comment]
On second thought, I don't think there's anything going wrong here in CockroachDB. There is no guarantee that the process is dead when `kill -9` returns. Process cleanup is usually fast, but perhaps it could be several seconds between when the kernel accepts the SIGKILL and when it actually cleans up the process's state.

@awoods187, are you using a script to run back-to-back TPCC roachtests, by chance? That would lend credence to my theory.

I think we should teach `roachprod stop` to actually wait until the processes are good and dead.

**Comment by awoods187** [comment]
@benesch  I'm running tpccbench which is a script that runs these tests back-to-back

**Comment by mberhault** [comment]
oh, my bad. This does call `rocksdb::LockFile` under the hood which is a normal posix file lock. This does get released on `SIGKILL`, but I'm not sure there are any guarantees about the delay.

**Comment by petermattis** [comment]
> I think we should teach roachprod stop to actually wait until the processes are good and dead.

Yeah, that is my thought (see my "wait" suggestion). We can change `stop` to do something like:

```
while $(kill -0 $PID 2>/dev/null); do
  sleep 1
done
```

**Comment by awoods187** [comment]
Any idea why this just manifested under the 9 node 64 cpu configuration? This is ~40the tpccbench test and first time seeing this outcome

**Comment by petermattis** [comment]
> Any idea why this just manifested under the 9 node 64 cpu configuration? 

Nope. Could be something to do with the number of cpus, though that is blind speculation.

Filed https://github.com/cockroachdb/roachprod/issues/219

**Comment by tschottdorf** [comment]
Fixed by cockroachdb/roachprod#219. @awoods187 please reopen if you see this again (but you shouldn't).

Make sure you upgrade your roachprod!

**Comment by awoods187** [comment]
Hi @tschottdorf I updated roachprod with  `go get -u github.com/cockroachdb/roachprod` and still received this error when I ran the test last night:

```
* ERROR: could not cleanup temporary directories from record file: could not lock temporary directory /mnt/data1/cockroach/cockroach-temp469838588, may still be in use: IO error: While lock file: /mnt/data1/cockroach/cockroach-temp469838588/TEMP_DIR.LOCK: Resource temporarily unavailable
*
Failed running "start"
E181019 06:26:40.441899 1 cli/error.go:230  exit status 1
Error: exit status 1
Failed running "start"
```

The cluster is still up: andy-1539913523-tpccbench-nodes-9-cpu-64

Also, unlike in other runs of tpcc-bench, I see warning of running in insecure mode after setting up the data set. This doesn't happen with other runs of tpccbench--it usually goes directly into the throughput tests. I observed this in the tests above as well. 

Full gist:
https://gist.github.com/awoods187/b27cd025e4c1e7c35486be0edef3ec7c

**Comment by tschottdorf** [comment]
What does `roachprod stop --help` output?

**Comment by tschottdorf** [comment]
> Also, unlike in other runs of tpcc-bench, I see warning of running in insecure mode after setting up the data set. This doesn't happen with other runs of tpccbench--it usually goes directly into the throughput tests. I observed this in the tests above as well.

That seems fine, that's just because the output is displayed along with the error.

**Comment by awoods187** [comment]
```
Andrews-MacBook-Pro-2:cockroach andrewwoods$ roachprod stop --help
Stop nodes on a cluster.

Stop roachprod created processes running on the nodes in a cluster, including
processes started by the "start", "run" and "ssh" commands. Every process
started by roachprod is tagged with a ROACHPROD=<node> environment variable
which is used by "stop" to locate the processes and terminate them. By default
processes are killed with signal 9 (SIGKILL) giving them no chance for a graceful
exit.

The --sig flag will pass a signal to kill to allow us finer control over how we
shutdown cockroach. The --wait flag causes stop to loop waiting for all
processes with the ROACHPROD=<node> environment variable to exit. Note that
stop will wait forever if you specify --wait with a non-terminating signal
(e.g. SIGHUP). --wait defaults to true for signal 9 (SIGKILL) and false for all
other signals.

The --tag flag can be used to to associate a tag with the process. This tag can
then be used to restrict the processes which are operated on by the status and
stop commands. Tags can have a hierarchical component by utilizing a slash
separated string similar to a filesystem path. A tag matches if a prefix of the
components match. For example, the tag "a/b" will match both "a/b" and
"a/b/c/d".


Node specification

  By default the operation is performed on all nodes in <cluster>. A subset of
  nodes can be specified by appending :<nodes> to the cluster name. The syntax
  of <nodes> is a comma separated list of specific node IDs or range of
  IDs. For example:

    roachprod stop marc-test:1-3,8-9

  will perform stop on:

    marc-test-1
    marc-test-2
    marc-test-3
    marc-test-8
    marc-test-9

Usage:
  roachprod stop <cluster> [--sig] [--wait] [flags]

Flags:
  -h, --help                       help for stop
      --insecure-ignore-host-key   don't check ssh host keys (default true)
      --sig int                    signal to pass to kill (default 9)
      --tag string                 the process tag
      --wait                       wait for processes to exit

Global Flags:
  -q, --quiet   disable fancy progress output
```

**Comment by benesch** [comment]
Tobi I changed the output of roachprod stop ton read “stopping and waiting”
so you can see that roachprod at least tried to wait for the process to
exit. It’s possible there’s still a bug there.

**Comment by tschottdorf** [comment]
Thanks.

@benesch if there isn't another root cause to this, something must've gone wrong with that PR.
The log has

> andy-1539913523-tpccbench-nodes-9-cpu-64: stopping and waiting

so it's definitely *trying* to wait.

**Comment by tschottdorf** [comment]
@awoods187 while we figure this out, try applying this patch into roachprod and rebuilding it:

```
diff --git a/install/cluster_synced.go b/install/cluster_synced.go
index edafe80..f84f487 100644
--- a/install/cluster_synced.go
+++ b/install/cluster_synced.go
@@ -124,6 +124,7 @@ func (c *SyncedCluster) Stop(sig int, wait bool) {
        display := fmt.Sprintf("%s: stopping", c.Name)
        if wait {
                display += " and waiting"
+               defer time.Sleep(10*time.Second)
        }
        c.Parallel(display, len(c.Nodes), 0, func(i int) ([]byte, error) {
                session, err := c.newSession(c.Nodes[i])
```

That'll just sleep for 10s after each kill, presumably enough for the process to actually shut down.

**Comment by awoods187** [comment]
Alright I applied the patch and will update in ~4 hours when the run completes

**Comment by tschottdorf** [comment]
@petermattis looks like something is still wrong with the `kill` thing. I wonder if there's a good way to create a process that will not immediately be reaped on `kill -9` to verify this without having to run large 64cpu machines.

**Comment by awoods187** [comment]
Before the last change that @tschottdorf had me do from above, i could produce this on every attempt of the 9 node 64 cpu test. I haven't modified roachprod since then so that I could continue testing.

**Comment by petermattis** [comment]
How long does it take to reproduce? Does it occur on the first instance of stopping and restarting the cluster? Does the problem occur on every node, or just one of the nodes?

**Comment by awoods187** [comment]
Well you have to wait for the restore to finish which is ~3hrs. However, it usually occurs on the first or second run of tpc-c at that point as evidenced by the gists above. I'm not sure on the nodes component. 

I do recall that this was only happening on the 9 node 64cpu configuration.

**Comment by petermattis** [comment]
Simply starting and stopping a 9-node x 64-cpu cluster in a loop did not reproduce any badness:

```
for i in {1..100}; do
    roachprod start peter-test
    roachprod stop peter-test
done
```

Guess I'll have to run `tpcc`.

**Comment by benesch** [comment]
Heh, I tried that too, with no luck. We could also teach `roachprod start` to wait for `fuser {data-dir}` to come up clean, and bail out with a helpful "you still have a cockroach proc running" error message if it doesn't after a few seconds.

**Comment by tschottdorf** [comment]
@knz might have a good idea on how to write a test program that can artificially delay releasing its resources when `kill -9`ed.

**Comment by knz** [comment]
You want a zombie process? 

Easy 5 steps:

1. mount NFS filesystem over UDP with `sync` option
2. run program that issues `write(2)` to a file on said filesystem repeatedly
3. pull the plug under the filesystem (remove network connection, kill NFS server, whatever)
4. verify process is blocked on IO
5. send SIGKILL to process

this way you'll get a zombie process until the NFS timeout kicks in (which may be never depending on NFS settings)

You can then see the process cleaned up by simply bringing NFS back.

I also noticed you didn't ask me how to explain how the lock could be held for 3 seconds after the process was killed. My first assumption would be the the VM's filesystem is not truly local and probably is on a network, and some network hangup caused the unlock operation to be delayed for 3 seconds.

However if that is the case, there should be OS warnings, check the output of `dmesg`.

**Comment by knz** [comment]
> how to write a test program that can artificially delay releasing its resources [when killed with SIGKILL]

btw this problem statement is nonsensical. When a process is sent SIGKILL, it never receives it. What happens from the point the kill is sent is entirely under responsibility of the OS. The process is stopped during that time and will never get a chance to recover and do anything about it.

**Comment by tschottdorf** [comment]
> btw this problem statement is nonsensical. When a process is sent SIGKILL, it never receives it. What happens from the point the kill is sent is entirely under responsibility of the OS. The process is stopped during that time and will never get a chance to recover and do anything about it.

I'm aware of that, but I don't think that the problem statement is incorrect. We want a program that manages to do stuff that leads to its resources being released later. Anyway, that's an academic discussion.

> I also noticed you didn't ask me how to explain how the crdb lock could be held for 3 seconds after the process was killed. My first assumption would be the the VM's filesystem is not truly local and probably is on a network, and some network hangup caused the unlock operation to be delayed for 3 seconds.

This is likely using GCE's pd-ssd and I doubt that they had network connectivity problems every time @awoods187 tried this. However, perhaps the fact that he was using 64 cpu machines is a red herring. Perhaps 64 cpu machines are privisioned in an environment that differs from the one we currently run in. Perhaps closing thousands of FDs at the same time leads to some sort of backpressure.

Thanks for pointing out the NFS solution, I wish there were something simpler though. Did you notice the detail that we wait until the process disappears from `ps axeww -o pid -o command` while stopping? Wouldn't you expect the zombie to be visible until strictly after its resources have been released?

**Comment by knz** [comment]
> Did you notice the detail that we wait until the process disappears from ps axeww -o pid -o command while stopping? 

No I had not noticed. If that is true, what you are witnessing here has nothing to do with zombie processes and "resources not being release *by that process* for some time" -- if there is no process entry for it any more, **the process does not exist any more**

> Wouldn't you expect the zombie to be visible until strictly after its resources have been released?

I repeat: if there is no process entry, there is no process. In the same way you wouldn't entertain the notion of the soul of the first man walking on the sun.

If there indeed was no process, that means that the OS (or the filesystem implementation) is doing something funky. Again, check the OS logs. Also file a complaint to the VM provider with your symptoms.

**Comment by knz** [comment]
That being said, I am being informed by hazy memory that unix advisory locks come with a "linger timeout" that kicks in after the owning process terminates. This should be investigated as well. I may be remembering wrong though.

**Comment by knz** [comment]
I am informed of the existence of the linux command `lslocks` which may provide clarity about what process owns the lingering lock.

**Comment by petermattis** [comment]
Thanks for the pointer, @knz. My biggest problem right now is that I can't reproduce this problem.

**Comment by petermattis** [comment]
`lslocks` definitely shows the locks:

```
~ lslocks | grep cockroach
cockroach        3216 POSIX   0B WRITE 0     0   0 /mnt/data1/cockroach/cockroach-temp192252000/LOCK
cockroach        3216 POSIX   0B WRITE 0     0   0 /mnt/data1/cockroach/LOCK
cockroach        3216 POSIX   0B WRITE 0     0   0 /mnt/data1/cockroach/cockroach-temp192252000/TEMP_DIR.LOCK
```

**Comment by knz** [comment]
Oh so there is a process entry after all.
Can you check it indeed exists in `/proc`?

I am surprised that `ps` does not show it.

What does `ps -A u | grep cockroach` say?

**Comment by knz** [comment]
Oh this entire discussion is predicated on a test in the code that "checks the ps output". How is this check performed? If the check is incorrect perhaps the loop is not waiting enough.

**Comment by knz** [comment]
Please double check this, but I recall seeing the full command line being erased from the process entry when it terminates, during the time it's zombie.

This means that the `sed` / `awk` game you're playing on the output of `ps` may cease to work when the process is defunct.

I would recommend working in two phases, first select the PIDs with a regular `ps | grep cockroach` and then search for the ROACHPROD things PID by PID.

**Comment by petermattis** [comment]
> I would recommend working in two phases, first select the PIDs with a regular ps | grep cockroach and then search for the ROACHPROD things PID by PID.

If you're looking at the code that powers `roachprod stop`, note that we don't look for `cockroach` processes. We kill any process containing the `ROACHPROD=<node>` env variable. The code is https://github.com/cockroachdb/roachprod/blob/master/install/cluster_synced.go#L137-L158.

I really wish I had a way to reproduce the problem, though. I'm a bit worried we're engaging in speculation here as to what the problem is, which makes me super hesitant to make any changes.

**Comment by petermattis** [comment]
It's not clear to me that a zombie `cockroach` process is the problem. A zombie process won't die so the `roachprod stop` should loop forever.

Note that I did try @awoods187 suggestion to run `roachtest bench tpccbench/nodes=9/cpu=64` but didn't encounter a problem before my cluster was killed when I left for the day. I'll give it another go tomorrow.

**Comment by knz** [comment]
@petermattis 

>  A zombie process won't die so the roachprod stop should loop forever.

Not quite. Please read what I wrote above. Currently `roachprod stop` uses the following command to "loop":

```go
    cmd := fmt.Sprintf(`count=0
while :; do
  pids=$(ps axeww -o pid -o command | \
    sed 's/export ROACHPROD=//g' | \
    awk '/ROACHPROD=(%d%s)[ \/]/ { print $1 }')
  if [ -z "${pids}" ]; then
    break
  fi
`, c.Nodes[i], c.escapedTag())

    if wait {
      cmd += `
  if [ ${count} -gt 0 ]; then
    sleep 1
  fi
  ((count++))
`
    }

    cmd += fmt.Sprintf(`
  kill -%d ${pids}
`, sig)
```

My point is the following: if, as I suspect, the full command line details are erased from the process entry when the process enters the zombie state, the command line arguments and environment will disappear. As a result the sed/awk dance with the string "ROACHPROD" will return zero PIDs, and the loop will erroneously conclude that the process has been cleaned up completely.

**Comment by petermattis** [comment]
> Please read what I wrote above.

I did read that, I just didn't believe you.

> My point is the following: if, as I suspect, the full command line details are erased from the process entry when the process enters the zombie state, the command line arguments and environment will disappear. 

I can verify that this occurs with a small program that creates a zombie process. On linux the process entry is still there, but the environment is gone:

```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>

int main(void) {
  pid_t pid;
  int status;
  
  fprintf(stderr, "parent %d\n", getpid());
  if ((pid = fork()) < 0) {
    perror("fork");
    exit(1);
  }
  
  if (pid == 0) {
    fprintf(stderr, "child %d\n", getpid());
    exit(0);
  }
  
  sleep(100);
  
  pid = wait(&status);
  if (WIFEXITED(status)) {
    fprintf(stderr, "\n\t[%d]\tProcess %d exited with status %d.\n",
            (int) getpid(), pid, WEXITSTATUS(status));
  }
  
  return 0;
}
```

Running this program on linux, `ps axeww -o pid -o command` that shows:

```
   24 ./zombie HOSTNAME=6e71995d3892 TERM=xterm PAGER=cat PATH=/opt/backtrace/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/x-tools/x86_64-unknown-linux-gnu/bin:/x-tools/x86_64-unknown-linux-musl/bin:/x-tools/x86_64-w64-mingw32/bin:/x-tools/aarch64-unknown-linux-gnueabi/bin:/x-tools/x86_64-apple-darwin13/bin PWD=/go/src/github.com/cockroachdb/cockroach GOTRACEBACK=all HOME=/home/roach SHLVL=1 GOPATH=/go _=./zombie
   25 [zombie] <defunct>
```

The part I still need to verify is when file locks get released. I would naively expect the zombie process to not be holding the file locks as it appears that the file descriptors are closed at this point, but easy enough to verify this.

**Comment by knz** [comment]
There are 2 sorts of file locks: path (inode) locks and file descriptor locks.

The path locks are owned by the process, not the file descriptors. Not sure they get auto-released on process termination. You could extend your test program and run `lslocks` to confirm what happens.

**Comment by petermattis** [comment]
> The part I still need to verify is when file locks get released.

Seems like file locks are released when a process is in the zombie state. At least for my simple way of creating a zombie process. Perhaps a zombie process created by writes to a network filesystem are different.

**Comment by petermattis** [comment]
Here is my current test program. The locking used here is taken directly from the RocksDB code (i.e. these are definitely the type of file locks we're using).

```
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/wait.h>

void lock() {
  int fd = open("/tmp/LOCK", O_CREAT|O_RDWR, 0644);
  if (fd < 0) {
    fprintf(stderr, "unable to create LOCK file: %s\n", strerror(errno));
    exit(0);
  }
  
  struct flock f;
  memset(&f, 0, sizeof(f));
  f.l_type = F_WRLCK;
  f.l_whence = SEEK_SET;
  f.l_start = 0;
  f.l_len = 0;
  int res = fcntl(fd, F_SETLK, &f);
  if (res == -1) {
    fprintf(stderr, "unable to lock LOCK file: %d %s\n", fd, strerror(errno));
    exit(0);
  }

  fprintf(stderr, "%d: LOCK acquired\n", getpid());
}

int main(void) {
  pid_t pid;
  int status;
  
  fprintf(stderr, "%d: parent\n", getpid());
  if ((pid = fork()) < 0) {
    perror("fork");
    exit(1);
  }
  
  if (pid == 0) {
    fprintf(stderr, "%d: child\n", getpid());
    lock();
    return 0;
  }

  sleep(1);
  lock();
  sleep(100);
  
  pid = wait(&status);
  if (WIFEXITED(status)) {
    fprintf(stderr, "\n\t[%d]\tProcess %d exited with status %d.\n",
            (int) getpid(), pid, WEXITSTATUS(status));
  }
  
  return 0;
}
```

**Comment by knz** [comment]
I suppose if the network filesystem has a pause / becomes unresponsive, the lock has to wait until the fs becomes responsive again (mandatory locks need to sync with the fs server).

**Comment by petermattis** [comment]
Sigh. I reproduced the problem running `roachtest bench -c peter-tpcc-9x64  tpccbench/nodes=9/cpu=64`, but I forgot to specify `--debug` and the cluster was wiped. I then tried reproducing using the tpcc-1k dataset instead (significantly faster to set up), but haven't seen a reproduction yet.

**Comment by petermattis** [comment]
I'm able to reproduce this problem whenever I run `roachtest bench -c peter-tpcc-9x64`. However, various attempts to reproduce with a faster debug cycle have failed. My most recent attempt involved a small tool which would fork a child process which would grab a few file locks, then kill the child using a similar mechanism to `roachprod stop` and immediately fork a new child to grab the same locks. This works fine both on my Mac and on a 64-cpu Linux box. I also tried having the child write a significant amount to disk while it was being killed. Nothing. I tried having the child grab thousands of file locks (20k in one test). Nope.

I'm going to admit defeat on a simple reproduction and add some instrumentation to `roachprod stop` instead.

**Comment by petermattis** [comment]
I managed another reproduction with the additional `roachprod` instrumentation. Let's see what we have. 

```
>>> roachprod stop: Fri Nov  2 18:56:48 UTC 2018
...
 7645 ./cockroach start --insecure --store=path=/mnt/data1/cockroach --log-dir=/home/pmattis/logs --cache=25% --max-sql-memory=25% --port=26257 --http-port=26258 --locality=cloud=gce,region=us-east1,zone=us-east1-b --join=35.231.18.223:26257 COCKROACH_ENABLE_RPC_COMPRESSION=false XDG_SESSION_ID=39 SHELL=/bin/bash SSH_CLIENT=108.54.201.109 56333 22 USER=pmattis MAIL=/var/mail/pmattis PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games PWD=/home/pmattis ROACHPROD=6 LANG=en_US.UTF-8 SHLVL=1 HOME=/home/pmattis LOGNAME=pmattis SSH_CONNECTION=108.54.201.109 56333 10.142.0.10 22 XDG_RUNTIME_DIR=/run/user/1008 _=./cockroach COCKROACH_BACKGROUND_RESTART=1
...
>>> roachprod start: Fri Nov  2 18:56:49 UTC 2018
...
 7645 [cockroach] <defunct>
...
COMMAND           PID  TYPE SIZE MODE  M START END PATH
...
cockroach        7645 POSIX   0B WRITE 0     0   0 /mnt/data1
...
cockroach        7645 POSIX   0B WRITE 0     0   0 /mnt/data1
...
cockroach        7645 POSIX   0B WRITE 0     0   0 /mnt/data1
```

Let me interpret this. `roachprod stop` is called and a `ps` listing shows the cockroach process as PID 7465. We immediately turn around and run `roachprod start` and a `ps` listing shows PID 7465 listed as `<defunct>`. The output from `lslocks` shows that process is still holding onto file locks even though we can't see its full command line or environment. So here we have proof that a zombie (defunct) process can still be holding on to file locks.

Not sure what I'm going to do. @knz's suggestion to grab the list of PIDs once and loop until they disappear is probably the most reasonable, though there is a slight danger that the PID is reused while the looping is taking place.

**Comment by benesch** [comment]
You could just loop until `lslocks` is clean, no?

**Comment by petermattis** [comment]
> You could just loop until `lslocks` is clean, no?

We might not be killing a cockroach process, though (e.g. if `roachprod stop --tag=foo --wait` is used). See my solution in https://github.com/cockroachdb/roachprod/pull/233. It suffers from the PID reuse problem, but I think that should be super rare.

**Comment by benesch** [comment]
Yeah, agreed that PID reuse is to rare to care about.
