### ISSUE TITLE
ci: "publish bleeding edge" failures often don't have issues opened for them

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#40414]
This build is pretty red. Not having it green means that we don't have these binaries stageable, and I think it also impacts the nightly roachtest builds which has the bleeding edge build as a prereq. We should not lose this kind of test coverage at this point.

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_MergeToMaster?branch=%3Cdefault%3E&buildTypeTab=overview

Nobody really checks this page, so we need to fix the issue posting ASAP.

Examples here: https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1567069131004000

Epic CRDB-10439

Jira issue: CRDB-5537

**Comment by bobvawter** [comment]
The sentry configuration is set to trigger alerts only if the incoming `environment` value is set to the exact value of `release`.  It looks like we're currently sending the git tag as the `environment` value, so the integration alert isn't actually firing for any new code.  I've temporarily set the alert to match on "issue first reported" in "all environments" to verify that the plumbing is still working.  Will dig into crdb code to see why we're not getting the expected string value.

**Comment by bobvawter** [comment]
#40514 just came in from `development`, so the webhook wiring is still ok.

**Comment by jordanlewis** [comment]
This issue isn't about sentry issues. It's about failures from the CI that gets run after PRs are merged to master. Feel free to ping me offline if you have questions about this.

**Comment by bobvawter** [comment]
Oops, on the wrong issue.

**Comment by tbg** [comment]
https://teamcity.cockroachdb.com/admin/editBuildRunners.html?id=buildType:Cockroach_MergeToMaster

Here's the build step that should do this.

Here's a build where that claims to have worked but didn't: https://teamcity.cockroachdb.com/viewLog.html?buildId=1471297&buildTypeId=Cockroach_MergeToMaster&tab=buildLog&_focus=167#_state=167

I would start by running that script locally against that build to see if the problem is in posting the issue or in detecting the failed tests.

**Comment by bobvawter** [comment]
I've been chasing the TeamCity API calls made by the `teamcity-post-failures.py` script and they're all looking like they still line up with what the script expects.  At this point, I think the next step is to check in some debugging changes and wait for it to not-report again.

**Comment by jordanlewis** [comment]
> and I think it also impacts the nightly roachtest builds which has the bleeding edge build as a prereq. 

I changed the nightlies to not depend on publish bleeding edge. They just pull the most recently generated binaries from the same branch. So at least that problem is solved.

**Comment by tbg** [comment]
FWIW, this issue is still going wild:

https://teamcity.cockroachdb.com/viewLog.html?buildId=1511685&buildTypeId=Cockroach_UnitTests

None of these failures had issues opened for them. They're new issues, so it's especially unfortunate that we don't get to see them. I'm not aware that anyone else is monitoring teamcity the way I feel forced I have to.

**Comment by jordanlewis** [comment]
I'll take a look at this very soon. Maybe the script has rotten.

**Comment by kenliu** [comment]
@jordanlewis did you get a chance to look into this?

**Comment by tbg** [comment]
teamcity-post-failures.py is now a noop on master; we use the same tool that nightly stress uses to post issues from release branches now. Will close this once I've confirmed it working.

**Comment by jordanlewis** [comment]
Re-ping on this. I haven't done anything on it, but it would be great if this script could do something on failure - I've gotten too used to polling #teamcity on Slack to find failures.

For example, check out this recent failure: https://teamcity.cockroachdb.com/viewLog.html?buildId=1995033&tab=buildResultsDiv&buildTypeId=Cockroach_MergeToMaster

I think this is happening during `mkrelease` for darwin?

**Comment by tbg** [comment]
I don't think we ever opened issues on master when the build failed (or did teamcity-post-failures.py do that as some sort of accidental side effect?), it was always for posting issues based on Go tests failing.
