### ISSUE TITLE
sql/pgwire: mishandling of error in multi-statement execution

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#4306]
```
root@:15432> begin; insert into x.y(a) values (1); end;
query error: pq: unexpected message 'C' in simple query execution
```

The expected error is "unknown database x". That's what we get it the final `end` is missing. And also if we execute outside of a transaction.

Probably somehow related to #4294, except here the error we get from libpq completely hides anything cockroach returned.

**Comment by tamird** [comment]
Possibly related to https://github.com/cockroachdb/pq/commit/de04a24934fb5fa9e4981a8246a8feb312eeb270

**Comment by petermattis** [comment]
I believe this is fixed in `cockroachdb/pq`, but we're not using that fork yet. See #4081.

**Comment by tamird** [comment]
Tested with https://github.com/cockroachdb/pq/commit/56c6975f8113c315d3165750ea4b21d5bdaa52d9 locally applied, still reproduces as written.

**Comment by tamird** [comment]
This works with our CLI against real postgres, so this is a server bug.

**Comment by petermattis** [comment]
Oh, sounds like a bug in `sql/pgwire` then.

**Comment by mjibson** [comment]
I don't think this is a pgwire problem:

```
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/lib/pq"
)

func main() {
	db, err := sql.Open("postgres", "host=127.0.0.1 port=15432 sslmode=disable")
	if err != nil {
		log.Fatal(err)
	}

	_, err = db.Exec("BEGIN; INSERT INTO x.y(a) VALUES (1); END;")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("success")
}
```

Outputs:

```
2016/02/17 18:33:25 pq: database "x" does not exist
```

Furthermore, adding the above query to `testdata/multi_statement` also prints the same database does not exist error. I'm pretty convinced this is a problem with the CLI.

**Comment by mjibson** [comment]
More evidence it's the CLI's fault: using `psql`:

```
root=> BEGIN; INSERT INTO x.y(a) VALUES (1); END;
BEGIN
ERROR:  database "x" does not exist
```

**Comment by mjibson** [comment]
Found. The problem is that `cli/sql_util.go` always calls `db.Query` (https://github.com/cockroachdb/cockroach/blob/33d0fa2238fcd02afacb66f4e27d1e0a40ed5fe2/cli/sql_util.go#L80) even if the statement doesn't return any results. lib/pq expects row data back instead of a command complete. No obvious fix comes to mind.

**Comment by mjibson** [comment]
Ah ha! We need to send a `Z` after the first error. Ok, evidently this is our problem. What long route around all this.
