### ISSUE TITLE
stability: segfault in sync.Pool. maybe?

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5311]
build sha: 4839bab

Usual setup: 4 nodes with 4 photos apps.
One node crashed after ~5h with:
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x6d1446]
```

There's something odd about panic parse on this one (and maybe others), it seems to be mangling a cgo trace.
Including both raw log and the one run through panicparse.

[node0.log.parse.txt](https://github.com/cockroachdb/cockroach/files/176675/node0.log.parse.txt)
[node0.log.txt](https://github.com/cockroachdb/cockroach/files/176674/node0.log.txt)

**Comment by tschottdorf** [comment]
duplicate of #5288.

@dt, do you have time to put in a stop-gap (basically just don't pass `opentracing.Trace` across a goroutine boundary, ever)?

**Comment by tschottdorf** [comment]
Hmm, this actually barfs really far down in the pool, which I don't understand. You're right, this is something weird down lower.

**Comment by tschottdorf** [comment]
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x6d1446]

goroutine 635 [running]:
runtime.throw(0x19c48e0, 0x2a)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc828d0ede0 sp=0xc828d0edc8
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc828d0ee30 sp=0xc828d0ede0
sync.(*Pool).pin(0xc82996e0c0, 0xf)
	/usr/local/go/src/sync/pool.go:158 +0x86 fp=0xc828d0ee50 sp=0xc828d0ee30
sync.(*Pool).Put(0xc82996e0c0, 0x17fefa0, 0xc820324000)
	/usr/local/go/src/sync/pool.go:72 +0x35 fp=0xc828d0eeb0 sp=0xc828d0ee50
github.com/opentracing/basictracer-go.(*spanImpl).FinishWithOptions(0xc820324000, 0x0, 0x143c65a900000000, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/opentracing/basictracer-go/span.go:124 +0x423 fp=0xc828d0efe0 sp=0xc828d0eeb0
github.com/opentracing/basictracer-go.(*spanImpl).Finish(0xc820324000)
	/go/src/github.com/opentracing/basictracer-go/span.go:100 +0x5d fp=0xc828d0f050 sp=0xc828d0efe0
github.com/opentracing/opentracing-go.(Span).Finish-fm()
	/go/src/github.com/cockroachdb/cockroach/util/tracing/tracer.go:103 +0x32 fp=0xc828d0f070 sp=0xc828d0f050
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send(0xc820376600, 0x7f15818ad680, 0xc8463cbcb0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc82176d958, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:455 +0x10ce fp=0xc828d0f3c8 sp=0xc828d0f070
```

`Put` and below up to the crash doesn't actually touch `x` (i.e. the span). This happening on a `Finish` though is too relevant to not matter. I don't understand this code well, but I suppose that an earlier Put of the same value could somehow lead to issues.

So, hopefully the same issue after all, though a more salient explanation would be nice.

**Comment by dt** [comment]
This was _probably_ fixed by #5317 but I still want to understand the actual panic before I'm willing to say that with confidence.

**Comment by tschottdorf** [comment]
I'm also interested in an explanation. Looks esoteric.

**Comment by petermattis** [comment]
Looks like this is still happening: https://github.com/cockroachdb/cockroach/issues/5371.

**Comment by tschottdorf** [comment]
Ok. We can presumably nail this down with a unit test. If anyone is interested I can provide guidance -- otherwise I'll do it.

**Comment by tschottdorf** [comment]
Regardless of demystifying this precise crash, here's a simple way that should catch all spans crossing goroutines (at least those which have calls on both goroutines):

```
diff --git a/util/tracing/tracer.go b/util/tracing/tracer.go
index aa00577..489047e 100644
--- a/util/tracing/tracer.go
+++ b/util/tracing/tracer.go
@@ -78,6 +78,7 @@ func defaultOptions(recorder func(basictracer.RawSpan)) basictracer.Options {
        opts.Recorder = CallbackRecorder(recorder)
        opts.NewSpanEventListener = basictracer.NetTraceIntegrator
        opts.DebugAssertUseAfterFinish = true // provoke crash on use-after-Finish
+       opts.DebugAssertSingleGoroutine = true
        return opts
 }
```

This crashes the `./sql` tests, and the location of the panic should reveal the goroutine it was passed into illegally (it's a shame thread safety is so hard here). Maybe we should simply put a `Mutex` on the `*basictracer.spanImpl` to make it truly thread safe.

**Comment by tschottdorf** [comment]
@petermattis pointed out that we were actually copying a `sync.Pool` by value in `basictracer`. That's clearly dangerous and virtually guaranteed to be the culprit. https://github.com/opentracing/basictracer-go/pull/16 should fix this upstream.
