### ISSUE TITLE
Can't escape single quote ' in Primary key query

### ISSUE THREAD

**Issue by rathboma** [cockroachdb/cockroach#56193]
**Describe the problem**

I have a table with a single quote character in the name `'`. I can create the table fine, but cannot retrieve primary key information from the `pg_*` tables.

In running the following query:

```sql
        SELECT a.attname as column_name, format_type(a.atttypid, a.atttypmod) AS data_type
        FROM   pg_index i
        JOIN   pg_attribute a ON a.attrelid = i.indrelid
                            AND a.attnum = ANY(i.indkey)
        WHERE  i.indrelid = 'public.tablewith''char'::regclass
        AND    i.indisprimary;


```
I get the error: `error: lexical error: unterminated string`

This query works fine in Postgres, and I believe I'm escaping the table name correctly?

This is part of a unit test suite for [Beekeeper Studio](https://github.com/beekeeper-studio/beekeeper-studio)

I'm using the latest version of the cockroachdb docker image.

EDIT

I've also tried parameterizing with `$1`, but I get a different error:

```sql
   SELECT a.attname as column_name, format_type(a.atttypid, a.atttypmod) AS data_type
    FROM   pg_index i
    JOIN   pg_attribute a ON a.attrelid = i.indrelid
                        AND a.attnum = ANY(i.indkey)
    WHERE  i.indrelid = $1::regclass
    AND    i.indisprimary;
```

`error: internal error: error in argument for $1: unsupported OID 2205 with format code FormatText`

^ This error happens with ANY table name, regardless of characters in the table name. Again this works fine in Postgres

**Comment by rathboma** [comment]
Hmm, not sure about this. Maybe I'm making a mistake. Let me close this until I figure it out

**Comment by rafiss** [comment]
@otan to confirm if #55607 fixes this.

**Comment by otan** [comment]
This is fixed in the next version of CockroachDB, open question as to whether we want to backport it.

```
demo@127.0.0.1:54951/defaultdb>         SELECT a.attname as column_name, format_type(a.atttypid, a.atttypmod) AS data_type
        FROM   pg_index i
        JOIN   pg_attribute a ON a.attrelid = i.indrelid
                            AND a.attnum = ANY(i.indkey)
        WHERE  i.indrelid = 'public.tablewith''char'::regclass
        AND    i.indisprimary;

ERROR: relation "public.tablewith'char" does not exist
SQLSTATE: 42P01
```

**Comment by rathboma** [comment]
Great, thanks! That fix doesn't seem to be related to the `$1` query argument syntax though right? So query args for `regclass` still won't work?

**Comment by otan** [comment]
No the $1 is different. I can take a look.
