### ISSUE TITLE
sql: Dropping table caused infinite `publish (count leases)` loop

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#6837]
A simple `DROP TABLE t;` statement caused an infinite logging loop of the following
while the sql shell hung waiting for a response:

```
I160521 01:04:11.596594 sql/lease.go:247  publish (count leases): descID=51 name=insert_into version=1 count=1
I160521 01:04:11.621678 sql/lease.go:247  publish (count leases): descID=51 name=insert_into version=1 count=1
...
```

When I killed my Cockroach server and started it up again, the table had been successfully deleted. Feel free to reassign.

**Comment by knz** [comment]
I believe this bug has been fixed for a while. Please check and close the issue if necessary.

**Comment by nvanbenschoten** [comment]
I have some memory of seeing this infinite loop earlier last week. I'm still not sure how to reproduce it, but I'm not convinced the issue has been resolved. Next time someone sees this, it would be nice to add some extra context to this issue (which it probably should have had in the first place).

**Comment by andreimatei** [comment]
I think this is probably similar to #9493 -  some node is not releasing a schema lease, probably after being shut down. I'm gonna close it in favor of that one.
