### ISSUE TITLE
sql: partial stats created empty stats entry when previous histogram contains max value

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#99377]
When a partial statistics collection at the extremes of an index scans zero rows, we create an empty statistics table entry. Would it be better to not create a statistics entry at all?

To reproduce:

```sql
SET enable_create_stats_using_extremes = on;
CREATE TABLE t (k INT PRIMARY KEY, a INT, INDEX (a));
INSERT INTO t VALUES (1, 10), (2, 20), (3, 9223372036854775807);
ANALYZE t;
INSERT INTO t VALUES (4, 40);
CREATE STATISTICS s ON a FROM t USING EXTREMES;
SHOW STATISTICS USING JSON FOR TABLE t;
```

Result (pretty-printed):

```json
[
  {
    "avg_size": 1,
    "columns": [
      "k"
    ],
    "created_at": "2023-03-23 14:32:54.130747",
    "distinct_count": 3,
    "histo_buckets": [
      {
        "distinct_range": 0,
        "num_eq": 1,
        "num_range": 0,
        "upper_bound": "1"
      },
      {
        "distinct_range": 0,
        "num_eq": 1,
        "num_range": 0,
        "upper_bound": "2"
      },
      {
        "distinct_range": 0,
        "num_eq": 1,
        "num_range": 0,
        "upper_bound": "3"
      }
    ],
    "histo_col_type": "INT8",
    "histo_version": 2,
    "null_count": 0,
    "row_count": 3
  },
  {
    "avg_size": 5,
    "columns": [
      "a"
    ],
    "created_at": "2023-03-23 14:32:54.130747",
    "distinct_count": 3,
    "histo_buckets": [
      {
        "distinct_range": 0,
        "num_eq": 1,
        "num_range": 0,
        "upper_bound": "10"
      },
      {
        "distinct_range": 0,
        "num_eq": 1,
        "num_range": 0,
        "upper_bound": "20"
      },
      {
        "distinct_range": 0,
        "num_eq": 1,
        "num_range": 0,
        "upper_bound": "9223372036854775807"
      }
    ],
    "histo_col_type": "INT8",
    "histo_version": 2,
    "null_count": 0,
    "row_count": 3
  },
  {
    "avg_size": 0,
    "columns": [
      "a"
    ],
    "created_at": "2023-03-23 14:32:54.154065",
    "distinct_count": 0,
    "full_statistic_id": 850367526120390700,
    "histo_col_type": "INT8",
    "histo_version": 2,
    "name": "s",
    "null_count": 0,
    "partial_predicate": "(a IS NULL) OR ((a < 10:::INT8) OR (a > 9223372036854775807:::INT8))",
    "row_count": 0
  }
]
```

Jira issue: CRDB-25852

**Comment by mgartner** [comment]
This may have been fixed - we should confirm this. See #125950.

**Comment by mgartner** [comment]
Assigning myself as a reminder to check during QA if this has been fixed.

**Comment by rytaft** [comment]
This still happens, but I think this is desired behavior. In particular, we want to make sure that a previous partial stats collection where there are some rows at the extremes is overridden if those rows are deleted. For example, this is a possible series of events:
1. insert 100 rows
2. full stat collection
3. insert 10 rows at the extremes
4. partial stat collection
5. delete those 10 rows
6. partial stat collection

The last partial stat collection (step 6) would show 0 rows, which is desirable. It's true that there is some unnecessary overhead in the case where there are no previous partial stats collections (or in the case where the full stat contains the max value), but I don't think the amount of overhead is significant enough that it's worth adding the extra logic and complexity. It may also be useful to have a record that the collection happened, even if it doesn't change the stats (for debugging purposes).

Going to close this since I don't think this is causing a problem.
